# Generated by Django 4.0.6 on 2022-07-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_type_id',
            new_name='task_type',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='taskcomment',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='taskcomment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='taskuser',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='taskuser',
            old_name='user_id',
            new_name='user',
        ),
    ]
